version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 207567776727.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - echo Current directory:
      - pwd
      - echo Directory contents:
      - ls -la
      - echo Moving to main_portal directory...
      - cd main_portal
      - echo Current directory after cd:
      - pwd
      - echo Directory contents after cd:
      - ls -la
      - docker build -t main-portal .
  post_build:
    commands:
      - echo Tagging and pushing the Docker image...
      - docker tag main-portal:latest 207567776727.dkr.ecr.us-west-2.amazonaws.com/main-portal:latest
      - docker push 207567776727.dkr.ecr.us-west-2.amazonaws.com/main-portal:latest